### PR TITLE
Add support for Python 3.13

### PR DESCRIPTION
**Pull request by ddelange**
hi @oconnor663 👋

on top of your awesome testing in the `py313` branch!

whack a mole cat meme gif

### CODE REVIEW

**Comment by oconnor663** [comment]
Ha, thanks for picking this up. I kept running into some combination of:

- Windows images didn't have Python 3.13 installed by default.
- Explicitly installing i686 Python broke Ubuntu somehow.

It looks like you're only setting `architecture: x86` for Windows i686 targets, and leaving it unset for Ubuntu. Is there some `maturin-action` magic that makes x64 setup not required for Ubuntu? Is it clear to you why it's required for win32 in the first place? In my head it's "something to do with linking", but I don't really understand the details, and I'm a little afraid of how magical (brittle?) all of this is :sweat_smile:

**Comment by oconnor663** [comment]
Also by the way, the Python API side of things has been stable for a while, so I'm thinking the next release will be 1.0. (There's a [tracking issue](https://github.com/oconnor663/blake3-py/issues/39).)

**Comment by ddelange** [comment]
"something to do with linking" is the current state of mind for me too in the case of the win32 wheel specifically. for linux this is probably irrelevant, because cross compiling doesn't rely on it (?)

**Comment by ddelange** [comment]
aha I see: for ubuntu-latest, maturin-action is pulling a docker image to build in. for mac and win, it is doing the build directly on the github runner.

**Comment by oconnor663** [comment]
@ddelange any chance you know why this run is failing? https://github.com/oconnor663/blake3-py/actions/runs/12079634972/job/33685800258

When I do this locally, it seems to work fine:
```
$ maturin build --release --out dist --interpreter 3.8 3.9 3.10 3.11 3.12 3.13
...
$ python -m twine check --strict dist/*
Checking dist/blake3-1.0.0-cp310-cp310-manylinux_2_34_x86_64.whl: PASSED
Checking dist/blake3-1.0.0-cp311-cp311-manylinux_2_34_x86_64.whl: PASSED
Checking dist/blake3-1.0.0-cp312-cp312-manylinux_2_34_x86_64.whl: PASSED
Checking dist/blake3-1.0.0-cp313-cp313-manylinux_2_34_x86_64.whl: PASSED
Checking dist/blake3-1.0.0-cp38-cp38-manylinux_2_34_x86_64.whl: PASSED
Checking dist/blake3-1.0.0-cp39-cp39-manylinux_2_34_x86_64.whl: PASSED
```

**Comment by ddelange** [comment]
let's see... last green run uses identical package versions:

```diff
- Successfully installed Pygments-2.18.0 SecretStorage-3.3.3 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.4.0 cryptography-44.0.0 docutils-0.21.2 idna-3.10 importlib-metadata-8.5.0 jaraco.classes-3.4.0 jaraco.context-6.0.1 jaraco.functools-4.1.0 jeepney-0.8.0 keyring-25.5.0 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-10.5.0 nh3-0.2.18 pkginfo-1.10.0 pycparser-2.22 readme-renderer-44.0 requests-2.32.3 requests-toolbelt-1.0.0 rfc3986-2.0.0 rich-13.9.4 twine-5.1.1 urllib3-2.2.3 zipp-3.21.0
+ Successfully installed Pygments-2.18.0 SecretStorage-3.3.3 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.4.0 cryptography-44.0.0 docutils-0.21.2 idna-3.10 importlib-metadata-8.5.0 jaraco.classes-3.4.0 jaraco.context-6.0.1 jaraco.functools-4.1.0 jeepney-0.8.0 keyring-25.5.0 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-10.5.0 nh3-0.2.18 pkginfo-1.10.0 pycparser-2.22 readme-renderer-44.0 requests-2.32.3 requests-toolbelt-1.0.0 rfc3986-2.0.0 rich-13.9.4 twine-5.1.1 urllib3-2.2.3 zipp-3.21.0
```

and the diff is ONLY the version bump. that makes zero sense to me.

fwiw, the twine check could be removed here because pypi publish action takes care of compliance checks.

**Comment by ddelange** [comment]
found it. thet bumped metadata version to 2.4 16 hours ago https://github.com/PyO3/maturin/releases/tag/v1.7.6

**Comment by ddelange** [comment]
fyi publish will only run on github release events, not on tag push events

**Comment by oconnor663** [comment]
I'm going to try removing the `twine` command, though if the Maturin action does the same thing internally, I might still need the version pin.

Incidentally, do you know why GH is kicking off the tests as well as a second copy of the dist job, in response to me publishing a release (not pushing a new commit)? Just from reading the YAML my expectation was that tests shouldn't run here.

image

**Comment by oconnor663** [comment]
(Apologies for turning this PR thread into a Q&A :sweat_smile: )

**Comment by ddelange** [comment]
no worries:) one is push event (pushing a tag) the other is release event.

to avoid it, you can revert to ky initial state of the PR where push event is only triggered for commits pushed to master: https://github.com/oconnor663/blake3-py/pull/45/commits/0c47e167c987c5b78a3f0816e7db3548df8fbfcc

**Comment by oconnor663** [comment]
Got it, thanks. This also seems to work: https://github.com/oconnor663/blake3-py/commit/6dbac66151b4608a047d05a230263f19e882110e

**Comment by ddelange** [comment]
i think that might still trigger a double run on commits pushed to pull requests: one for push event and one for pull_request event. but maybe that's not true (anymore)

**Comment by ddelange** [comment]
or maybe thats only true for branches that are pushed by you, and not for forks

**Pull request closed without merging**
