### PR TITLE
Build Apple Silicon wheels

### LINKED ISSUE #20: binary wheel for apple silicon (M1 cpu)
... would be nice to have.

### PR DESCRIPTION
**Pull request by messense**
packaging workflow run example: https://github.com/messense/blake3-py/actions/runs/1188683206

Closes #20

### CODE REVIEW

**Comment by oconnor663** [comment]
Thank you! This will save me a lot of trouble. In other projects (https://github.com/oconnor663/blake3-py/blob/master/.github/workflows/upload_github_release_asset.py#L14-L19) I've tried to put together a "rerelease" mechanism, so that I can release new builds like this without tagging a totally new project version. I might try something similar here.

**Comment by messense** [comment]
I think you can try automate something like that on GitHub Actions with the [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) trigger.

**Comment by oconnor663** [comment]
(Oh actually we do set `CARGO_BUILD_TARGET`. I'm slowing remembering this stuff.)

**Comment by oconnor663** [comment]
Here are some of the build failures I'm seeing: https://github.com/oconnor663/blake3-py/runs/3969628042?check_suite_focus=true

**Comment by oconnor663** [comment]
Sorry for all the comment spam. The immediate cause of these is probably that blake3 v1.1.0 enabled the NEON implementation by default, but I'm not totally sure.

**Comment by messense** [comment]
Opened https://github.com/oconnor663/blake3-py/pull/23

**Pull request merged**
